// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DEMO.Entities
{
    [Table("CourseInstructor")]
    [Index("InstructorId", Name = "IX_CourseInstructor_InstructorId")]
    public partial class CourseInstructor
    {
        [Key]
        public int CourseId { get; set; }
        [Key]
        public int InstructorId { get; set; }
        public int Evaluate { get; set; }

        [ForeignKey("CourseId")]
        [InverseProperty("CourseInstructors")]
        public virtual Course Course { get; set; }
        [ForeignKey("InstructorId")]
        [InverseProperty("CourseInstructors")]
        public virtual Instructor Instructor { get; set; }
    }
}