// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DEMO.Entities
{
    [Index("TopicId", Name = "IX_Courses_TopicId")]
    public partial class Course
    {
        public Course()
        {
            CourseInstructors = new HashSet<CourseInstructor>();
            StudentCourses = new HashSet<StudentCourse>();
        }

        [Key]
        public int Id { get; set; }
        public int Duration { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [StringLength(1)]
        [Unicode(false)]
        public string Description { get; set; }
        public int? TopicId { get; set; }

        [ForeignKey("TopicId")]
        [InverseProperty("Courses")]
        public virtual Topic Topic { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<CourseInstructor> CourseInstructors { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<StudentCourse> StudentCourses { get; set; }
    }
}