// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DEMO.Entities
{
    [Index("InstructorId", Name = "IX_Departments_InstructorId", IsUnique = true)]
    public partial class Department
    {
        public Department()
        {
            Students = new HashSet<Student>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public int InstructorId { get; set; }

        [ForeignKey("InstructorId")]
        [InverseProperty("Department")]
        public virtual Instructor Instructor { get; set; }
        [InverseProperty("DepartmentNavigation")]
        public virtual Instructor InstructorNavigation { get; set; }
        [InverseProperty("Department")]
        public virtual ICollection<Student> Students { get; set; }
    }
}