// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DEMO.Entities
{
    [Index("DepartmentId", Name = "IX_Instructors_DepartmentId", IsUnique = true)]
    public partial class Instructor
    {
        public Instructor()
        {
            CourseInstructors = new HashSet<CourseInstructor>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Bonus { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Salary { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal HourRate { get; set; }
        [Required]
        public string Address { get; set; }
        public int DepartmentId { get; set; }

        [ForeignKey("DepartmentId")]
        [InverseProperty("InstructorNavigation")]
        public virtual Department DepartmentNavigation { get; set; }
        [InverseProperty("Instructor")]
        public virtual Department Department { get; set; }
        [InverseProperty("Instructor")]
        public virtual ICollection<CourseInstructor> CourseInstructors { get; set; }
    }
}