// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DEMO.Entities
{
    [Table("StudentCourse")]
    [Index("CourseId", Name = "IX_StudentCourse_CourseId")]
    public partial class StudentCourse
    {
        [Key]
        public int StudentId { get; set; }
        [Key]
        public int CourseId { get; set; }
        public int Grade { get; set; }

        [ForeignKey("CourseId")]
        [InverseProperty("StudentCourses")]
        public virtual Course Course { get; set; }
        [ForeignKey("StudentId")]
        [InverseProperty("StudentCourses")]
        public virtual Student Student { get; set; }
    }
}